//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetQuantity
    {
        public int AssetQuantityID { get; set; }
        public int AssetID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime WarrantyExpiryDate { get; set; }
        public Nullable<bool> IsQRIssued { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BuildingID { get; set; }
    
        public virtual AssetMaster AssetMaster { get; set; }
        public virtual Building Building { get; set; }
    }
}
