//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSAsset
    {
        public int AssetID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string UserName { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> IsQRIssued { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
