//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDepartment
    {
        public int DepartmentID { get; set; }
        public int BuildingID { get; set; }
        public string DepartmentName { get; set; }
        public int LoginID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Login Login { get; set; }
    }
}
