//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedQRDetail
    {
        public string QRID { get; set; }
        public int RequestID { get; set; }
        public string EmployeeID { get; set; }
        public string MaterialSubCategory { get; set; }
        public Nullable<int> TotalIssuedQty { get; set; }
        public string VendorDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
