//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialMasterList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialMasterList()
        {
            this.MaterialStocks = new HashSet<MaterialStock>();
        }
    
        public int MasterListID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public string Units { get; set; }
        public int AvailableQuantity { get; set; }
        public System.DateTime MaterialUpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int MinimumLimit { get; set; }
        public bool IsLowStockAlertSent { get; set; }
        public Nullable<int> UniversityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStock> MaterialStocks { get; set; }
    }
}
