//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialStock
    {
        public int MaterialStockID { get; set; }
        public int MaterialID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public decimal ReceivedQty { get; set; }
        public decimal AvailableQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Make { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string PONumber { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MaterialMasterList MaterialMasterList { get; set; }
    }
}
