//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialAvailable
    {
        public int MaterialStockID { get; set; }
        public string MaterialName { get; set; }
        public string VendorName { get; set; }
        public string VendorPhoneNumber { get; set; }
        public string VendorEmail { get; set; }
        public decimal ReceivedQty { get; set; }
        public decimal AvailableQty { get; set; }
        public string Make { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> UniversityID { get; set; }
    }
}
